import type { Metadata } from 'next';
import { merriweather, rubik } from './fonts';
import './globals.css';
import './providers';
import { Navigation } from './nav';
import Providers from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${merriweather.variable} ${rubik.variable}`}
      suppressHydrationWarning
    >
      <body>
        <Providers>
          <div className="dark:bg-slate-800 dark:text-slate-100 bg-white text-slate-600 flex flex-col h-screen">
            <header>
              <Navigation />
            </header>
            <main className="max-h-full overflow-y-scroll">{children}</main>
            <footer></footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
