import type { Metadata } from "next";
import { merriweather, inter } from "./fonts"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${merriweather.variable} ${inter.variable} dark`}>
      <body className="dark:bg-dark-bg-dim dark:text-dark-fg bg-light-bg-0 text-light-fg">{children}</body>
    </html>
  );
}
