import type { Metadata } from "next";
import { merriweather, inter } from "./fonts";
import "./globals.css";
import { Providers } from "./providers";
import { Navigation } from "./nav";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${merriweather.variable} ${inter.variable}`} suppressHydrationWarning>
      <body>
        <Providers>
          <div className="dark:bg-dark-bg-dim dark:text-dark-fg bg-light-bg-0 text-light-fg flex flex-col h-screen">
            <div>
                <Navigation />
            </div>
            <div className="max-h-full overflow-y-scroll">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
